baseURL = 'https://wanhaogongsi.com/'
languageCode = 'ja'
title = '丸好公司'
theme = 'hugo.386'

[params]
    # The name to display as main title in the home page
    mainpagetitle = "丸好公司"

    # The subtitle to display under the title in the home page
    mainpagesubtitle = "歓迎来到丸好公司" 

    # The description of your website. It will be displayed in the home page
    mainpagedesc = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."

    # Show the "built on Hugo" disclaimer
    showhugo = true

    # Urls for social networks
    twitter = "https://x.com/wanhaogongsi/"
    github = "https://github.com/tenax66/wanhaogongsi"

    # Enables or disables the loading animations. false activates them. Default is false.
    loadfastload = false

    # Sets the speed for the page loading effect. Default is 1.0.
    loadspeedfactor = 1.0

    # Enables or disables the second flyby cursor. Default is false.
    loadonepass = false

[params.copyright]
    name = "wanhaogongsi"

    # The url to use as link in the copyright name in the footer. Leave empty to use none.
    url = ""

    # Text to go before copyright information
    prefix = ""

    # Text to go between copyright and hugo disclaimer (if enabled)
    suffix = ""

[menu]
  # This displays buttons in the navbar to access your contents
  [[menu.main]]
    identifier = "about" # An unique identifier for the button
    name = "About"       # A display name for the button
    url = "/about/"      # The path to the content. It can lead to a single page (like here)
    weight = 10          # A number to order the buttons in the navbar

  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/post/"       # The path can lead to a content folder too.
    weight = 20
